package br.com.zup.gerenciadorCompeticoes.enuns;

public enum Time {

    ATLETICO_MG,FLAMENGO,PALMEIRAS,CORINTHIANS,FORTALEZA,BRAGANTINO,FLUMINENSE,CEARA,INTERNACIONAL,AMERICA_MG,SANTOS,
    CUIABA,ATHLETICO_PR,SAO_PAULO,ATLETICO_GO,JUVENTUDE,GREMIO,SPORT,CHAPECOENSE

}
